datasets:
  cc_sbu:
    data_type: images
    build_info:
      #storage: /public/home/mswanghao/project/MiniGPT-GPU-OPT1/data/cc_sbu/cc_sbu_dataset/{00000..00009}.tar
      storage: /public/home/mswanghao/cocodata/mscoco/{00000..00059}.tar
